---
tabWidth: 4
useTabs: true
semi: true
singleQuote: false
trailingComma: "es5"
bracketSpacing: true
arrowParens: "always"
printWidth: 100

overrides:
    - files:
          - "*.html"
          - "*.jsx"
          - "*.ejs"
          - "*.hbs"
      options:
          parser: "html"
